import { NextResponse } from 'next/server'
import { createServerSupabaseClient } from '@/lib/supabase/server'
import { OpenAIImageProvider } from '@/lib/providers/openai-image'
import { HttpImageProvider } from '@/lib/providers/http-adapters'
import { ProviderRegistry } from '@/lib/providers/registry'
import { persistGeneratedAsset } from '@/lib/providers/persist'
import type { ImageGenerationProvider } from '@/lib/providers/types'
export const dynamic='force-dynamic'
const styles={cinematic:'cinematic film still, sophisticated composition, dramatic natural lighting, realistic materials, rich depth, premium color grading',photorealistic:'high-end photorealistic photography, physically plausible light, natural textures, fine detail, professional camera aesthetic',documentary:'authentic documentary photography, natural available light, candid realism, grounded details, editorial composition',illustration:'premium editorial digital illustration, refined shapes, expressive composition, detailed artistic finish','3d':'high-end 3D render, detailed materials, global illumination, cinematic composition, polished production quality',anime:'original anime-inspired illustration, expressive composition, detailed environment, polished animation-film quality',vintage:'vintage analog photography aesthetic, subtle film grain, period-appropriate color response, tactile texture',minimal:'premium minimalist visual design, strong negative space, clean geometry, restrained composition',fantasy:'original cinematic fantasy concept art, atmospheric depth, intricate worldbuilding, dramatic lighting, premium detail',surreal:'surreal fine-art image, imaginative visual metaphor, coherent dreamlike composition, sophisticated lighting'} as const
type Style=keyof typeof styles
export async function POST(request:Request){const supabase=await createServerSupabaseClient();const{data:{user}}=await supabase.auth.getUser();if(!user)return NextResponse.json({error:'Unauthorized'},{status:401});const body=await request.json().catch(()=>null) as {projectId?:string;prompt?:string;style?:Style}|null;const projectId=body?.projectId?.trim(),prompt=body?.prompt?.trim();if(!projectId||!prompt||prompt.length>4000)return NextResponse.json({error:'Valid projectId and prompt are required'},{status:400});const{data:project}=await supabase.from('projects').select('id').eq('id',projectId).eq('owner_id',user.id).maybeSingle();if(!project)return NextResponse.json({error:'Project not found'},{status:404});const style:Style=body?.style&&body.style in styles?body.style:'cinematic',requestId=crypto.randomUUID(),context={ownerId:user.id,projectId,requestId};const enhanced=`${prompt}\n\nVisual direction: ${styles[style]}. Create an original, coherent, professional-quality image with strong subject clarity, intentional composition, accurate anatomy and perspective where applicable, clean details, and no accidental text, logos or watermarks.`;try{const registry=new ProviderRegistry<ImageGenerationProvider>().register(new OpenAIImageProvider()).register(new HttpImageProvider());let generated;try{generated=await registry.execute(['openai-image','image-fallback'],p=>p.generateImage(context,enhanced))}catch(error){const details=error instanceof Error?error.message:'Unknown provider error';console.error('Image provider failure',{requestId,details});const match=details.match(/OpenAI image generation failed \((\d{3})\)/);const code=match?Number(match[1]):null;const message=code===401?'OpenAI rechazó la clave API.':code===403?'OpenAI rechazó el acceso al modelo o al proyecto.':code===429?'OpenAI alcanzó un límite de uso o de facturación.':code===400?'OpenAI rechazó los parámetros de generación.':code&&code>=500?'El servicio de imágenes de OpenAI no está disponible.':'El proveedor de imágenes no pudo completar la generación.';return NextResponse.json({error:message,stage:'provider',providerStatus:code,requestId},{status:503})}generated.metadata={...(generated.metadata??{}),style,originalPrompt:prompt};try{const asset=await persistGeneratedAsset(context,'image',generated);return NextResponse.json({requestId,style,provider:generated.provider,asset},{status:201})}catch(error){console.error('Image persistence failure',{requestId,details:error instanceof Error?error.message:'Unknown persistence error'});return NextResponse.json({error:'La imagen se generó, pero no se pudo guardar en la Biblioteca. No repitas la generación.',stage:'storage',requestId},{status:500})}}catch(error){console.error('Image request failure',{requestId,details:error instanceof Error?error.message:'Unknown request error'});return NextResponse.json({error:'No se pudo completar la solicitud de imagen.',stage:'request',requestId},{status:500})}}
