'use client'

import { FormEvent, useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { StudioShell } from '../components/studio-shell'
import { getSupabaseBrowserClient } from '@/lib/supabase/client'
import type { OpportunityRow } from '@/lib/types/database'

const statusLabel:Record<string,string>={discovered:'A · Descubierta',research_needed:'B · Investigación necesaria',experiment_candidate:'C · Candidata a experimento',candidate:'C · Candidata a experimento',experiment_approved:'D · Experimento aprobado',discarded:'E · Descartada'}

export default function OpportunitiesPage(){
 const supabase=getSupabaseBrowserClient();const router=useRouter();const[items,setItems]=useState<OpportunityRow[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[busyId,setBusyId]=useState<string|null>(null)
 async function load(){setLoading(true);setError('');const{data:{user},error:authError}=await supabase.auth.getUser();if(authError){setError(authError.message);setLoading(false);return}if(!user){setError('Sesión requerida.');setLoading(false);return}const{data,error}=await supabase.from('opportunities').select('*').order('created_at',{ascending:false});if(error)setError(error.message);else setItems((data??[]) as OpportunityRow[]);setLoading(false)}
 useEffect(()=>{void load()},[])
 async function setStatus(o:OpportunityRow,status:string){setBusyId(o.id);setError('');try{const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Sesión requerida.');const{error}=await supabase.from('opportunities').update({status}).eq('id',o.id).eq('owner_id',user.id);if(error)throw error;await load()}catch(e){setError(e instanceof Error?e.message:'No se pudo actualizar la oportunidad.')}finally{setBusyId(null)}}
 async function createProject(e:FormEvent<HTMLFormElement>,o:OpportunityRow){e.preventDefault();setBusyId(o.id);setError('');try{const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Sesión requerida.');const{data,error}=await supabase.from('projects').insert({owner_id:user.id,name:o.title,description:`Oportunidad ${o.source_platform}${o.query?` · ${o.query}`:''}`,status:'draft',target_platforms:['youtube']}).select('id').single();if(error)throw error;const{error:updateError}=await supabase.from('opportunities').update({project_id:data.id,status:'experiment_candidate'}).eq('id',o.id).eq('owner_id',user.id);if(updateError)throw updateError;router.push(`/projects?project=${data.id}`)}catch(e){setError(e instanceof Error?e.message:'No se pudo crear el proyecto.')}finally{setBusyId(null)}}
 return <StudioShell title="Oportunidades"><div className="hero"><div><small>DECISIÓN CONTROLADA</small><h2>Oportunidades accionables</h2><p>Evalúa señales con el ciclo A–E y conviértelas en proyectos sin saltarte las puertas de aprobación.</p></div><div className="status"><b>{items.length}</b><span>oportunidades disponibles</span><span>Publicación real bloqueada</span></div></div>{error&&<p className="error">{error}</p>}{loading?<p>Cargando…</p>:<div className="grid">{items.map(o=><article key={o.id}><small>{o.region||'Global'} · {o.language||'—'}</small><h3>{o.title}</h3><p>Estado: {statusLabel[o.status]||o.status}</p><p>Fuente: {o.source_platform}{o.confidence!=null?` · confianza ${o.confidence}`:''}</p><div className="statusActions"><button disabled={busyId===o.id} onClick={()=>void setStatus(o,'research_needed')}>Investigar</button><button disabled={busyId===o.id} onClick={()=>void setStatus(o,'experiment_candidate')}>Candidata</button><button disabled={busyId===o.id} onClick={()=>void setStatus(o,'experiment_approved')}>Aprobar experimento</button><button disabled={busyId===o.id} onClick={()=>void setStatus(o,'discarded')}>Descartar</button></div><form onSubmit={e=>void createProject(e,o)}><button disabled={busyId===o.id||Boolean(o.project_id)}>{o.project_id?'Proyecto creado':'Convertir en proyecto'}</button></form><small>“Experimento aprobado” no autoriza publicación, gasto ni contacto externo.</small></article>)}</div>}</StudioShell>
}
