import { NextResponse } from 'next/server'
import { createServerSupabaseClient } from '@/lib/supabase/server'
import { FalH3TurboVideoProvider } from '@/lib/providers/fal-video'
import { HttpVideoProvider } from '@/lib/providers/http-adapters'
import { ProviderRegistry } from '@/lib/providers/registry'
import { persistGeneratedAsset } from '@/lib/providers/persist'
import type { VideoGenerationProvider } from '@/lib/providers/types'
export const dynamic='force-dynamic'
export async function POST(request:Request){const supabase=await createServerSupabaseClient();const{data:{user}}=await supabase.auth.getUser();if(!user)return NextResponse.json({error:'Unauthorized'},{status:401});const body=await request.json().catch(()=>null) as {projectId?:string;prompt?:string}|null;const projectId=body?.projectId?.trim(),prompt=body?.prompt?.trim();if(!projectId||!prompt||prompt.length>4000)return NextResponse.json({error:'Valid projectId and prompt are required'},{status:400});const{data:project}=await supabase.from('projects').select('id').eq('id',projectId).eq('owner_id',user.id).maybeSingle();if(!project)return NextResponse.json({error:'Project not found'},{status:404});const requestId=crypto.randomUUID(),context={ownerId:user.id,projectId,requestId};try{const registry=new ProviderRegistry<VideoGenerationProvider>().register(new FalH3TurboVideoProvider()).register(new HttpVideoProvider()).register(new HttpVideoProvider('video-fallback','VIDEO_FALLBACK_ENDPOINT','VIDEO_FALLBACK_API_KEY'));const generated=await registry.execute(['fal-h3-turbo'],p=>p.generateVideo(context,prompt));const asset=await persistGeneratedAsset(context,'video',generated);return NextResponse.json({requestId,provider:generated.provider,asset},{status:201})}catch{return NextResponse.json({error:'Video generation is temporarily unavailable.',requestId},{status:503})}}
