-- Cerebro Studio schema baseline
-- Mirrors the initial application schema already deployed to Supabase.
-- Additive/idempotent where practical so repository history documents the security model.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.projects (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  description text,
  status text not null default 'draft',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.assets (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  project_id uuid references public.projects(id) on delete cascade,
  kind text not null,
  storage_path text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.opportunities (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  source_platform text not null,
  source_query text,
  region text,
  language text,
  status text not null default 'discovered',
  confidence numeric,
  observed_metrics jsonb not null default '{}'::jsonb,
  calculated_metrics jsonb not null default '{}'::jsonb,
  evidence jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.channel_connections (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  platform text not null,
  external_channel_id text,
  display_name text,
  scopes text[] not null default '{}',
  status text not null default 'disconnected',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.metric_snapshots (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  channel_connection_id uuid references public.channel_connections(id) on delete cascade,
  observed_at timestamptz not null default now(),
  observed_metrics jsonb not null default '{}'::jsonb,
  calculated_metrics jsonb not null default '{}'::jsonb
);

create table if not exists public.publication_jobs (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  project_id uuid references public.projects(id) on delete cascade,
  platform text not null,
  status text not null default 'draft',
  idempotency_key text,
  payload jsonb not null default '{}'::jsonb,
  approved_at timestamptz,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  unique(owner_id, platform, idempotency_key)
);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  action text not null,
  entity_type text not null,
  entity_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.projects enable row level security;
alter table public.assets enable row level security;
alter table public.opportunities enable row level security;
alter table public.channel_connections enable row level security;
alter table public.metric_snapshots enable row level security;
alter table public.publication_jobs enable row level security;
alter table public.audit_log enable row level security;

-- Owner-scoped policies. audit_log intentionally has no client insert/update/delete policy.
do $$
begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='profiles' and policyname='profiles_owner_all') then
    create policy profiles_owner_all on public.profiles for all using (id = auth.uid()) with check (id = auth.uid());
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='projects' and policyname='projects_owner_all') then
    create policy projects_owner_all on public.projects for all using (owner_id = auth.uid()) with check (owner_id = auth.uid());
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='assets' and policyname='assets_owner_all') then
    create policy assets_owner_all on public.assets for all using (owner_id = auth.uid()) with check (owner_id = auth.uid());
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='opportunities' and policyname='opportunities_owner_all') then
    create policy opportunities_owner_all on public.opportunities for all using (owner_id = auth.uid()) with check (owner_id = auth.uid());
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='channel_connections' and policyname='channel_connections_owner_all') then
    create policy channel_connections_owner_all on public.channel_connections for all using (owner_id = auth.uid()) with check (owner_id = auth.uid());
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='metric_snapshots' and policyname='metric_snapshots_owner_all') then
    create policy metric_snapshots_owner_all on public.metric_snapshots for all using (owner_id = auth.uid()) with check (owner_id = auth.uid());
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='publication_jobs' and policyname='publication_jobs_owner_all') then
    create policy publication_jobs_owner_all on public.publication_jobs for all using (owner_id = auth.uid()) with check (owner_id = auth.uid());
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='audit_log' and policyname='audit_log_owner_read') then
    create policy audit_log_owner_read on public.audit_log for select using (owner_id = auth.uid());
  end if;
end $$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles(id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'display_name', new.email))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();
